Rails.application.routes.draw do
  devise_for :users
  root 'restaurant_table_management#home'
  get 'restaurant_reservation/index_reservation'
  get 'restaurant_reservation/index_basket'
  get 'restaurant_reservation/new_schedule/:restaurant_id'=>'restaurant_reservation#new_schedule'
  get 'restaurant_reservation/restaurantInfo/:restaurant_id'=>'restaurant_reservation#restaurantInfo'
  post 'restaurant_reservation/create_schedule/:restaurant_id' => 'restaurant_reservation#create_schedule'
  get 'restaurant_reservation/edit_reservation/:reservation_id'=>'restaurant_reservation#edit_reservation'
  patch 'restaurant_reservation/update_reservation/:reservation_id'=>'restaurant_reservation#update_reservation'
  get 'restaurant_reservation/destroy_reservation/:reservation_id'=>'restaurant_reservation#destroy_reservation'
  get 'restaurant_recommendation/my_page'
  get 'restaurant_recommendation/get_recommendation'
  get 'restaurant_recommendation/get_shopping_bag'
  get 'restaurant_recommendation/priority_setting'
  get 'restaurant_recommendation/search_setting'
  get 'restaurant_recommendation/select_food_category'
  post 'restaurant_recommendation/create_priority'
  get 'restaurant_recommendation/add_to_shopping_bag/:restaurant_id' => 'restaurant_recommendation#add_to_shopping_bag'
  get 'restaurant_recommendation/remove_from_shopping_bag/:restaurant_id' => 'restaurant_recommendation#remove_from_shopping_bag'
  patch 'restaurant_recommendation/update_priority'
  get 'restaurant_recommendation/select_location_division'
  get 'restaurant_recommendation/search_food_category'
  get 'restaurant_recommendation/search_restaurant'
  get 'restaurant_recommendation/search_location_category'
  get 'restaurant_recommendation/search_location_division/:category_id' => 'restaurant_recommendation#search_location_division'
  get 'restaurant_table_management/index_restaurant'
  delete 'restaurant_table_management/delete_restaurant/:restaurant_id' => 'restaurant_table_management#delete_restaurant'
  patch 'restaurant_table_management/update_restaurant/:restaurant_id' =>'restaurant_table_management#update_restaurant'
  get 'restaurant_table_management/edit_restaurant/:restaurant_id' => 'restaurant_table_management#edit_restaurant'
  get 'restaurant_table_management/index_restaurant'
  get 'restaurant_table_management/new_restaurant'
  post 'restaurant_table_management/create_restaurant'
  get 'restaurant_table_management/index_table/:restaurant_id' => 'restaurant_table_management#index_table'
  post 'restaurant_table_management/create_table/:restaurant_id' => 'restaurant_table_management#create_table'
  get 'restaurant_table_management/new_table/:restaurant_id' => 'restaurant_table_management#new_table'
  get 'restaurant_table_management/index_schedule/:restaurant_id/:table_id'=> 'restaurant_table_management#index_schedule'
  get 'restaurant_table_management/new_schedule/:restaurant_id/:table_id' => 'restaurant_table_management#new_schedule'
  post 'restaurant_table_management/create_schedule/:restaurant_id/:table_id' => 'restaurant_table_management#create_schedule'
  patch 'restaurant_table_management/seated/:table_id' => 'restaurant_table_management#seated'
  patch 'restaurant_table_management/out/:table_id' => 'restaurant_table_management#out'
  patch 'restaurant_table_management/start/:schedule_id' => 'restaurant_table_management#start'
  patch 'restaurant_table_management/end/:schedule_id' => 'restaurant_table_management#end'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end
